ShaulisBlog/Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShaulisBlog.Models
{
    public class BlogPost
    {
        [Key]
        public int ID { get; set; }

        [ForeignKey("Author")]
        public int WriterId { get; set; }

        public Fan Author { get; set; }

        public String Content { get; set; }

        public String Title { get; set; }

        public DateTime PostDate { get; set; }

        public DateTime? UpdateDate { get; set; }

        public List<Comment> Comments { get; set; }
    }
}

ShaulisBlog/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShaulisBlog.Models;
using System.Globalization;

namespace ShaulisBlog.Controllers
{
    public class BlogPostsController : Controller
    {
        private ShaulisBlogContext db = new ShaulisBlogContext();

        // GET: BlogPosts
        public ActionResult Index()
        {
            var blogPosts = db.BlogPosts.Include(b => b.Author).Include(b => b.Comments).Include("Comments.Author");

            // Creates the list of gender values for the filter combobox
            ViewBag.genders = new SelectList(Enum.GetNames(typeof(Gender)));

            return View(blogPosts.ToList());
        }

        // Redirect to view of Advanced Search
        public ActionResult AdvancedSearch()
        {
            return View();
        }

        // Redirect to the group by user view
        public ActionResult GroupBy()
        {
            var blogPosts = db.BlogPosts.Include(b => b.Author).ToList();

            var blogPostsGrouped =
                (from post in blogPosts
                 group post by post.WriterId);

            return View(blogPostsGrouped);
        }

        // This function searches by crossing multiple fields
        public ActionResult StartAdvancedSearch(string author, string title, DateTime? date = null)
        {
            var blogPosts = db.BlogPosts.Include(b => b.Author).Include(b => b.Comments).Include("Comments.Author");

            if (!String.IsNullOrEmpty(author))
            {
                blogPosts = blogPosts.Where(b => (b.Author.FirstName + " " + b.Author.LastName).Contains(author) ||
                                       (b.Author.LastName + " " + b.Author.FirstName).Contains(author));
            }

            if (!String.IsNullOrEmpty(title))
            {
                blogPosts = blogPosts.Where(b => b.Title.Contains(title));
            }

            if(date != null)
            {
                blogPosts = blogPosts.Where(b => DbFunctions.TruncateTime(b.PostDate) == DbFunctions.TruncateTime(date.Value));
            }

            // Creates the list of gender values for the filter combobox
            ViewBag.genders = new SelectList(Enum.GetNames(typeof(Gender)));

            return View("Index", blogPosts.ToList());
        }

        public ActionResult Search(string searchString)
        {
            var blogPosts = db.BlogPosts.Include(b => b.Author).Include(b => b.Comments).Include("Comments.Author");
            if (!String.IsNullOrEmpty(searchString))
            {
                blogPosts = blogPosts.Where(b => b.Author.FirstName.Contains(searchString) || 
                                                 b.Author.LastName.Contains(searchString) || 
                                                 b.Content.Contains(searchString) || 
                                                 b.Title.Contains(searchString));
            }

            // Creates the list of gender values for the filter combobox
            ViewBag.genders = new SelectList(Enum.GetNames(typeof(Gender)));

            return View("Index", blogPosts.ToList());
        }

        public ActionResult FilterByGender()
        {
            var blogPosts = db.BlogPosts.AsQueryable();
            string gender = "";
            if (!String.IsNullOrEmpty(Request.Form["genders"]))
            {
                gender = Request.Form["genders"];
                Gender wantedGender = (Gender)Enum.Parse(typeof(Gender), gender);

                blogPosts =
                    (from post in blogPosts
                     join fan in db.Fans on post.WriterId equals fan.ID
                     where fan.Gender == wantedGender
                     select post).Include(b => b.Author).Include(b => b.Comments).Include("Comments.Author");
            }

            // Creates the list of gender values for the filter combobox and preserve the selected option
            ViewBag.genders = new SelectList(Enum.GetNames(typeof(Gender)), gender);

            return View("Index", blogPosts.ToList());
        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        public ActionResult ViewComments(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }

            return RedirectToAction("Index", "Comments", new { postId = id });
        }

        // GET: BlogPosts/Create
        public ActionResult Create()
        {
            ViewBag.WriterId = new SelectList(db.Fans, "ID", "FirstName");
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Content")] BlogPost blogPost)
        {
            if (ModelState.IsValid)
            {
                var date = DateTime.Now;
                blogPost.PostDate = date;
                blogPost.UpdateDate = date;
                blogPost.WriterId = LoginController.getUserId();
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.WriterId = new SelectList(db.Fans, "ID", "FirstName", blogPost.WriterId);
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            ViewBag.WriterId = new SelectList(db.Fans, "ID", "FirstName", blogPost.WriterId);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,WriterId,Content,Title,PostDate")] BlogPost blogPost)
        {
            if (ModelState.IsValid)
            {
                blogPost.UpdateDate = DateTime.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.WriterId = new SelectList(db.Fans, "ID", "FirstName", blogPost.WriterId);
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult EditComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return RedirectToAction("Edit", "Comments", new { id = id });
        }

        public ActionResult Comment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            
            return RedirectToAction("Create", "Comments", new { postId = id });
        }

        public ActionResult DeleteComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }

            return RedirectToAction("Delete", "Comments", new { Id = id });
        }

        public ActionResult DetailsComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }

ShaulisBlog/Views/BlogPosts/AdvancedSearch.cshtml
@model ShaulisBlog.Models.BlogPost

@{
    ViewBag.Title = "Blog Posts Advanced Search";
}

<h2>Blog Posts Advanced Search</h2>
    
@using (Html.BeginForm("StartAdvancedSearch", "BlogPosts", new
{ author = "Author", date = "Date", postTitle="PostTitle"}))
{
    <p>
        <input type="text" name="Author" placeholder="Author" />
        <input type="text" name="Title" placeholder="Title" />
        <br />
        <input type="date" name="Date" />
        <input type="submit" value="Search" />
    </p>
}

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

ShaulisBlog/Views/BlogPosts/Create.cshtml
@model ShaulisBlog.Models.BlogPost

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BlogPost</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShaulisBlog/Views/BlogPosts/Delete.cshtml
@model ShaulisBlog.Models.BlogPost

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShaulisBlog/Views/BlogPosts/Details.cshtml
@model ShaulisBlog.Models.BlogPost

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShaulisBlog/Views/BlogPosts/Edit.cshtml
@model ShaulisBlog.Models.BlogPost

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BlogPost</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.WriterId)
        @Html.HiddenFor(model => model.PostDate)

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShaulisBlog/Views/BlogPosts/GroupBy.cshtml
@model IEnumerable<IGrouping<int, ShaulisBlog.Models.BlogPost>>

@{
    ViewBag.Title = "GroupBy";
}

<h2>GroupBy</h2>
@foreach (var group in Model)
{

    <h1>
        @group.First().Author.FirstName @Html.Raw(" ") @group.First().Author.LastName
    </h1>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Single().Single().Author.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Single().Single().Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Single().Single().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Single().Single().PostDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Single().Single().UpdateDate)
        </th>
    </tr>
@foreach (var item in group.OrderByDescending(x => x.UpdateDate))
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Author.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdateDate)
        </td>
    </tr>
}

</table>
<hr />
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<br />

ShaulisBlog/Views/BlogPosts/Index.cshtml
@using ShaulisBlog.Controllers

@model IEnumerable<ShaulisBlog.Models.BlogPost>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Search", "BlogPosts", new { searchString = "SearchString" }))
{
    <p>
        Find by name: @Html.TextBox("SearchString", "", new { placeholder = "Author\\Title\\Content.." })
        <input type="submit" value="Search" />
    </p>
}

@using (Html.BeginForm("FilterByGender", "BlogPosts"))
{
    <p>
        @Html.DropDownList("genders")
        <input type="submit" value="Filter" />
    </p>
}

<p>
    @Html.ActionLink("Advanced search", "AdvancedSearch")
    @Html.Raw(" | ")
    @Html.ActionLink("Group by author", "GroupBy")
</p>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@if (LoginController.IsAdmin())
{
    <p>
        @Html.ActionLink("Statistics", "Statistics")
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.OrderByDescending(post => post.UpdateDate)) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Author.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdateDate)
        </td>
        <td>
            @if (LoginController.canPerfom(item.Author.ID, "Edit"))
            { 
                @Html.ActionLink("Edit", "Edit", new { id=item.ID })          
                @Html.Raw(" | ")
            } 
            @if (LoginController.canPerfom(item.Author.ID, "Delete"))
            {
                @Html.ActionLink("Delete", "Delete", new { id = item.ID });
                @Html.Raw(" | ")
            }
            
            @Html.ActionLink("Comment", "Comment", new { id = item.ID })
        </td>
    </tr>
    if (item.Comments != null && item.Comments.Count > 0) {
        var comments = item.Comments.OrderByDescending(comm => comm.UpdateDate).ToList();
        <tr>
            <td colspan="5" class="comments-table-area">
                <table class="table comments-table">
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Comments.First().Title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Comments.First().Content)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Comments.First().CommentDate)
                        </th>
                        <th></th>
                    </tr>

                    @for (var index = 0; index < comments.Count && index < 5; index++)
                    {
                        var comment = comments[index];
                        <tr>
                            <td>
                                @comment.Author.FirstName @comment.Author.LastName
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => comment.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => comment.Content)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => comment.CommentDate)
                            </td>
                            <td>
                                @if (LoginController.canPerfom(comment.Author.ID, "Edit"))
                                {
                                    @Html.ActionLink("Edit", "EditComment", new { id = comment.ID })
                                    @Html.Raw(" | ")
                                }
                                @if (LoginController.canPerfom(comment.Author.ID, "Delete"))
                                {
                                    @Html.ActionLink("Delete", "DeleteComment", new { id = comment.ID })
                                }
                            </td>
                        </tr>
                    }
                    <tr>
                        <td colspan="2">
                            @item.Comments.Count comments total.
                        </td>
                        <td colspan="3">
                            @Html.ActionLink("View all comments..", "ViewComments", new { id = item.ID })
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    }
}

</table>

ShaulisBlog/Views/BlogPosts/Statistics.cshtml
<script src="//d3js.org/d3.v3.min.js"></script>
<style>
    
graphDiv {
        font: 10px sans-serif;
    }

    .axis path,
    .axis line {
        fill: none;
        stroke: #000;
        shape-rendering: crispEdges;
    }

    .bar {
        fill: steelblue;
    }

    .x.axis path {
        display: none;
    }
</style>

@{
    ViewBag.Title = "Statistics";
}

<h2>Blog posts posting statistics</h2>
<h4>For the last six months, by gender</h4>

<div class="graphDiv"></div>

@Scripts.Render("~/Scripts/PostStatistics.js")